# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NevaTask' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NevaTask
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'Kingfisher'
     pod 'RxAlamofire'
    pod 'SVProgressHUD'

  target 'NevaTaskTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NevaTaskUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
